### ISSUE TITLE
module.outpost_cloud9_bastion - The environment creation failed

### ISSUE THREAD

**Issue by cmlccie** [Outposts-Test-Lab/otl-service-launcher#2]
When creating a Cloud9 bastion instance on the OTL Outpost with `outpost_cloud9 = true`, I received the following error(s) from Terraform and Cloud9's CloudFormation deployment.

**Terraform CLI Error:**
```
Error: Reason: The environment creation failed with the error: The following resource(s) failed to create: [Instance]. Rollback requested by user..
```

**Cloud9 CloudFormation Error:**
```
CREATE_FAILED	Instance i-0bf88563d67e2f80a failed to stabilize. Current state: shutting-down. Reason: Server.InternalError: Internal error on launch
```

*Full Terraform CLI output and CloudFormation events:*
[outpost_cloud9_bastion_deployment_error.txt](https://github.com/Outposts-Test-Lab/otl-service-launcher/files/5983397/outpost_cloud9_bastion_deployment_error.txt)

**Comment by adam-imeson** [comment]
This usually happens because the target AWS account has EBS default encryption set to a non-default KMS key, and the Cloud9 service endpoint hasn't been allowed by that KMS key's policy. This isn't solvable within this Terraform stack but is instead an issue with how we deploy our OTL test environments. More generally it exposes an issue with how Cloud9 fails to surface this error to customers.

I will fix this by making an update to our onboarding logic, and the behavior will be solved over the next couple of weeks as the racks cycle tenants. I've also contacted the Cloud9 service team to ask them to improve the error message here.

In the meantime we can manually edit the KMS policy in the target account to allow Cloud9.

**Comment by adam-imeson** [comment]
We've added Cloud9 permissions to our onboarding logic, so this should be solved going forward.
